name: CI_new
on: workflow_dispatch

jobs: 
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: first-step
        run: | 
          echo "Hello"
          echo date
          echo "First step"
      - name: second-step
        run: echo "2nd step"
